project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc-title: Contents
    toc: true
    toc-depth: 3
    toc-location: right

website:
  navbar:
      pinned: TRUE
      search: TRUE
      collapse: false
      right:
        - text: "<b>Menu<b>"
          menu:
            - icon: house-door-fill
              text: "Home"
              href: index.html
            - icon: card-text
              text: "CV"
              href: about.html
            - icon: pin-map-fill
              text: "UFO Sightings Project"
              href: UFOs.html 
            - icon: bar-chart-fill
              text: "Data Visualization"
              href: datavis.html 
            - icon: github
              text: "Github"
              href: "https://github.com/EmilyRStern/"
